language: python
python:
  - "2.7"
# commands to install dependencies
install:
  - pip install multiqc
  - pip install .
# commands to run tests
script:
  - multiqc .
  - multiqc . -o tests/multiqc_report_dev -t default_dev -k json
